


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."check_email_exists"("check_email" "text") RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM auth.users
    WHERE email = check_email
  );
END;
$$;


ALTER FUNCTION "public"."check_email_exists"("check_email" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- 1. Create the user profile (your existing logic)
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    new.id, 
    -- This pulls the part of the email before the @ as a temporary username
    split_part(new.email, '@', 1), 
    '' -- Default empty string for avatar
  );

  -- 2. Create default shelves for the new user (new logic)
  INSERT INTO public.shelves (user_id, name, is_default)
  VALUES 
    (NEW.id, 'Reading', true),
    (NEW.id, 'Read', true),
    (NEW.id, 'Want to Read', true),
    (NEW.id, 'Favorites', true);

  RETURN new;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."books" (
    "isbn" "text" NOT NULL,
    "title" "text",
    "authors" "text"[],
    "description" "text",
    "cover_image" "text",
    "page_count" integer,
    "publisher" "text",
    "source" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "release_year" "text"
);


ALTER TABLE "public"."books" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "text" "text",
    "userId" "uuid",
    "postId" bigint
);


ALTER TABLE "public"."comments" OWNER TO "postgres";


ALTER TABLE "public"."comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "senderId" "uuid",
    "receiverId" "uuid",
    "data" "text"
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


ALTER TABLE "public"."notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."postLikes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "postId" bigint,
    "userId" "uuid"
);


ALTER TABLE "public"."postLikes" OWNER TO "postgres";


ALTER TABLE "public"."postLikes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."postLikes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."posts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "body" "text",
    "file" "text",
    "userId" "uuid",
    "post_type" "text" DEFAULT ''::"text",
    "rating" numeric DEFAULT '0'::numeric,
    "book_isbn" "text" DEFAULT ''::"text"
);


ALTER TABLE "public"."posts" OWNER TO "postgres";


ALTER TABLE "public"."posts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."posts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "username" "text",
    "first_name" "text",
    "avatar_url" "text",
    "website" "text",
    "bio" "text",
    "read_count" integer DEFAULT 0,
    "reading_count" integer DEFAULT 0,
    "shelved_count" integer DEFAULT 0,
    "post_count" integer DEFAULT 0,
    "friend_count" integer DEFAULT 0,
    "follow_count" integer DEFAULT 0,
    "last_name" "text",
    CONSTRAINT "username_length" CHECK (("char_length"("username") >= 3))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."shelf_books" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "shelf_id" "uuid" NOT NULL,
    "book_isbn" "text" NOT NULL,
    "added_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."shelf_books" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."shelves" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "is_default" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."shelves" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."userBooks" (
    "uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "book_id" "text" DEFAULT ''::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "shelf_id" smallint
);


ALTER TABLE "public"."userBooks" OWNER TO "postgres";


ALTER TABLE ONLY "public"."books"
    ADD CONSTRAINT "books_pkey" PRIMARY KEY ("isbn");



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."postLikes"
    ADD CONSTRAINT "postLikes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."shelf_books"
    ADD CONSTRAINT "shelf_books_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."shelf_books"
    ADD CONSTRAINT "shelf_books_shelf_id_book_isbn_key" UNIQUE ("shelf_id", "book_isbn");



ALTER TABLE ONLY "public"."shelves"
    ADD CONSTRAINT "shelves_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."shelves"
    ADD CONSTRAINT "shelves_user_id_name_key" UNIQUE ("user_id", "name");



ALTER TABLE ONLY "public"."userBooks"
    ADD CONSTRAINT "userBooks_pkey" PRIMARY KEY ("uuid");



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_postId_fkey" FOREIGN KEY ("postId") REFERENCES "public"."posts"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."comments"
    ADD CONSTRAINT "comments_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_receiverId_fkey" FOREIGN KEY ("receiverId") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."postLikes"
    ADD CONSTRAINT "postLikes_postId_fkey" FOREIGN KEY ("postId") REFERENCES "public"."posts"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."postLikes"
    ADD CONSTRAINT "postLikes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_book_isbn_fkey" FOREIGN KEY ("book_isbn") REFERENCES "public"."books"("isbn") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shelf_books"
    ADD CONSTRAINT "shelf_books_book_isbn_fkey" FOREIGN KEY ("book_isbn") REFERENCES "public"."books"("isbn") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shelf_books"
    ADD CONSTRAINT "shelf_books_shelf_id_fkey" FOREIGN KEY ("shelf_id") REFERENCES "public"."shelves"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shelves"
    ADD CONSTRAINT "shelves_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."userBooks"
    ADD CONSTRAINT "userBooks_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("isbn") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."userBooks"
    ADD CONSTRAINT "userBooks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow public to view shelves" ON "public"."shelf_books" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Allow public to view shelves" ON "public"."shelves" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Anyone can view posts" ON "public"."posts" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all" ON "public"."books" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all" ON "public"."userBooks" FOR SELECT USING (true);



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Users can comment on posts" ON "public"."comments" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "userId"));



CREATE POLICY "Users can delete books from their shelves" ON "public"."shelf_books" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."shelves"
  WHERE (("shelves"."id" = "shelf_books"."shelf_id") AND ("shelves"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete their own comments on posts" ON "public"."comments" FOR DELETE USING (("auth"."uid"() = "userId"));



CREATE POLICY "Users can delete their own posts" ON "public"."posts" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "userId"));



CREATE POLICY "Users can delete their own shelves" ON "public"."shelves" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert books to their shelves" ON "public"."shelf_books" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."shelves"
  WHERE (("shelves"."id" = "shelf_books"."shelf_id") AND ("shelves"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can insert their own shelves" ON "public"."shelves" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can like posts" ON "public"."postLikes" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "userId"));



CREATE POLICY "Users can only create posts that belong to them selves" ON "public"."posts" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "userId"));



CREATE POLICY "Users can remove their like on a post" ON "public"."postLikes" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "userId"));



CREATE POLICY "Users can see likes on posts" ON "public"."postLikes" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update their own post" ON "public"."posts" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "userId"));



CREATE POLICY "Users can update their own shelves" ON "public"."shelves" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view books on their shelves" ON "public"."shelf_books" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."shelves"
  WHERE (("shelves"."id" = "shelf_books"."shelf_id") AND ("shelves"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can view comments on posts" ON "public"."comments" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Users can view their own shelves" ON "public"."shelves" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "allow all" ON "public"."notifications" USING (true);



ALTER TABLE "public"."books" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."postLikes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."posts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."shelf_books" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."shelves" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."userBooks" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";















































































































































































































































































































































































































































































































GRANT ALL ON FUNCTION "public"."check_email_exists"("check_email" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."check_email_exists"("check_email" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."check_email_exists"("check_email" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";






























GRANT ALL ON TABLE "public"."books" TO "anon";
GRANT ALL ON TABLE "public"."books" TO "authenticated";
GRANT ALL ON TABLE "public"."books" TO "service_role";



GRANT ALL ON TABLE "public"."comments" TO "anon";
GRANT ALL ON TABLE "public"."comments" TO "authenticated";
GRANT ALL ON TABLE "public"."comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."postLikes" TO "anon";
GRANT ALL ON TABLE "public"."postLikes" TO "authenticated";
GRANT ALL ON TABLE "public"."postLikes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."postLikes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."postLikes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."postLikes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."posts" TO "anon";
GRANT ALL ON TABLE "public"."posts" TO "authenticated";
GRANT ALL ON TABLE "public"."posts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."posts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."shelf_books" TO "anon";
GRANT ALL ON TABLE "public"."shelf_books" TO "authenticated";
GRANT ALL ON TABLE "public"."shelf_books" TO "service_role";



GRANT ALL ON TABLE "public"."shelves" TO "anon";
GRANT ALL ON TABLE "public"."shelves" TO "authenticated";
GRANT ALL ON TABLE "public"."shelves" TO "service_role";



GRANT ALL ON TABLE "public"."userBooks" TO "anon";
GRANT ALL ON TABLE "public"."userBooks" TO "authenticated";
GRANT ALL ON TABLE "public"."userBooks" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Allow authenticated uploads 1rma4z_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'posts'::text));



  create policy "Anyone can upload an avatar."
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'avatars'::text));



  create policy "Avatar images are publicly accessible."
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "anon and authenticated users can view posts 1rma4z_0"
  on "storage"."objects"
  as permissive
  for select
  to anon, authenticated
using ((bucket_id = 'posts'::text));



